### ISSUE TITLE
Bonsai filter for CentOS prevents usage with CentOS

### ISSUE THREAD

**Issue by cabrel** [sensu-plugins/sensu-plugins-disk-checks#123]
In .bonsai.yml the entity.system.platform is set to rhel for the CentOS filter. On CentOS, that property is 'centos' and in order for the asset to be applied properly it should be set to centos or (the more preferred option) the filter changed to entity.system.platform_family.

Offending line: https://github.com/sensu-plugins/sensu-plugins-disk-checks/blob/master/.bonsai.yml#L19

sensuctl entity state for a CentOS 7 box:
![2019-05-22_12-57-43](https://user-images.githubusercontent.com/2131665/58197242-7a91fa00-7c91-11e9-87f6-c64f275ac984.png)

**Comment by nixwiz** [comment]
Fixed in #141
