### ISSUE TITLE
Adaptive thresholds?

### ISSUE THREAD

**Issue by joshbeard** [sensu-plugins/sensu-plugins-disk-checks#14]
I'm curious what the thoughts are on providing "adaptive thresholds" for the percentages.  For instance, 10% free of a 100GB volume is arguably more severe than 10% free of a 10TB volume.  Adapting the thresholds based on volume size would allow for a single check to be more fitting of different volumes without triggering undesirable alerts.

This features is available in check_mk's disk check.  I've forked the Sensu plugin here and added this functionality in if anyone would like to take a look and consider it:
https://github.com/sensu-plugins/sensu-plugins-disk-checks/compare/master...joshbeard:adaptive?expand=1

The idea is that you provide base percentages for warning and critical thresholds.  These percentages are slightly adjusted for larger filesystems based on a "magic factor" the user can provide.  A magic factor of 0 (the default) does no adjustment at all (current behavior).  There's also an option to modify the normalized factor, where volumes of exactly that size will not be adjusted.  Finally, there's an option to specify a minimum size to adjust, so volumes smaller than this will not be adapted.

This can be visualized with [WolframAlpha](https://www.wolframalpha.com/input/) with something like the following:

    y = 100 - (100-P)*(N^(1-m))/(x^(1-m)), y = P for x in 0 to 1024

_Where P = base percentage, N = normalize factor, and m = magic factor_

**Comment by mattyjones** [comment]
@joshbeard I am more than happy to think about it. Off-hand I see no problem with it as long as you can use the check without the thresholds, which it looks like you can.

**Comment by joshbeard** [comment]
Correct.  These additions don't change the default behavior at all.
