### ISSUE TITLE
check-disk-fail, check-disk, check-fs-writeable missing

### ISSUE THREAD

**Issue by nhinds** [sensu-plugins/sensu-plugins-disk-checks#23]
The README claims `check-disk-fail`, `check-disk` and `check-fs-writeable` exist (and their files, `bin/check-disk-fail.rb`, `bin/check-disk.rb`, `bin/check-fs-writeable.rb`).

No such files seem to exist in this repository. Perhaps they were missed in a check-in, or the README is out of date.

**Comment by eheydrick** [comment]
Looks like `check-disk-fail` was never brought over from the old repo. I think the intention was to rewrite it to be cross-platform. `check-disk` was rewritten as `check-disk-usage` and is cross-platform. `check-fs-writable` is now in the [sensu-plugins-filesystem-checks](https://github.com/sensu-plugins/sensu-plugins-filesystem-checks) repo. I'm going to remove the lies from the README. Thanks for noticing!

**Comment by eheydrick** [comment]
Resolved via https://github.com/sensu-plugins/sensu-plugins-disk-checks/commit/4a87d52e50ebd660338208c47de3b2f4d8e67531
