### ISSUE TITLE
stderr: ERROR:  While executing gem ... (Gem::Security::Exception)

### ISSUE THREAD

**Issue by maj0rhav0c** [sensu-plugins/sensu-plugins-disk-checks#24]
Gem was updated 3 days ago - went to update today (via Ansible) - this cert fails now? Other plugins installed successfully (elasticsearch, rabbitmq). I can work around it by forcing previous version of gem on install, or by disabling security certificate validation. 

stderr: ERROR:  While executing gem ... (Gem::Security::Exception)
    root cert /CN=djberg96/DC=gmail/DC=com is not trusted
failed: [server-hostname-redacted] => (item=sensu-plugins-disk-checks) => {"changed": true, "cmd": ["/opt/sensu/embedded/bin/gem", "install", "sensu-plugins-disk-checks", "-P", "MediumSecurity"], "delta": "0:00:03.039079", "end": "2015-12-14 16:41:13.238870", "item": "sensu-plugins-disk-checks", "rc": 1, "start": "2015-12-14 16:41:10.199791", "warnings": []}

**Comment by eheydrick** [comment]
That's odd, the gems are signed by "/CN=mattjones/DC=yieldbot/DC=com". Can you do a `gem cert -l` to show the certs installed. When I have that cert installed I can successfully install the latest version of the plugin with the `-P MediumSecurity` flag.

**Comment by eheydrick** [comment]
The issue is that the `sys-filesystem` gem is now signed. So you'll need the cert for `sys-filesystem` installed if you're checking certs. That cert is at https://github.com/djberg96/sys-filesystem/blob/ffi/certs/djberg96_pub.pem. I'm going to add a note to the README about needing certs for dependencies.

**Comment by maj0rhav0c** [comment]
Thank you, @eheydrick - was out a few days and when I came back, all working again. 
``` bash
user_id@redacted:/opt/sensu/embedded/bin# ./gem cert -l
/CN=mattjones/DC=yieldbot/DC=com
```
Didn't have to add the `sys-filesystem` part mentioned. Used the same cert install instructions found in the general install & setup instructions found on this page: 
http://sensu-plugins.io/docs/installation_instructions.html
