### ISSUE TITLE
CheckDisk WARNING: / 86.47% bytes usage (0 TiB/0 TiB)

### ISSUE THREAD

**Issue by Salamek** [sensu-plugins/sensu-plugins-disk-checks#25]
Title says it all

CheckDisk WARNING: / 86.47% bytes usage **(0 TiB/0 TiB)**

**Comment by analytically** [comment]
Mind investigating a bit more? What's the actual usage? I'd happily accept a PR.

**Comment by Salamek** [comment]
@analytically fixed in https://github.com/sensu-plugins/sensu-plugins-disk-checks/pull/29

**Comment by eheydrick** [comment]
Fix released in 1.1.3.
