### ISSUE TITLE
UUID mount cause an error

### ISSUE THREAD

**Issue by kindred** [sensu-plugins/sensu-plugins-disk-checks#38]
When I run the 'check-fstab-mounts' check, I get the following error with UUID mounts.

Check failed to run: No such file or directory @ realpath_rec - /opt/sensu/embedded/bin/UUID=dcb162f9-fb35-431f-ag25-ba0c64143b21, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:66:in `realpath'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:66:in`realpath'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:66:in `block (2 levels) in check_mounts'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:66:in`select'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:66:in `block in check_mounts'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:57:in`each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:57:in `check_mounts'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-fstab-mounts.rb:74:in`run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in class:CLI'"]

**Comment by hughnet** [comment]
+ 1

**Comment by enachi** [comment]
+1

**Comment by eheydrick** [comment]
Hi, which platform are you seeing this on? Can you paste your fstab too. Trying to repro this.

**Comment by eheydrick** [comment]
bump.

**Comment by kindred** [comment]
Hey Sorry, been quite busy with work of late.

I'll have to grab the fstab when I'm at work, as it was a work box I was
building at the time.

**Comment by lkosz** [comment]
I have such error too, and it is caused by line:
`UUID=f1fe78c1-d922-4de7-8af4-6088d8616c15 swap                    swap    defaults        0 0`

**Comment by rosscdh** [comment]
+1

**Comment by hughnet** [comment]
Here is what I did to fix this.

as root:
#blkid -U [Block ID]

example output:
blkid -U 21503aea-7477-45b2-bf4e-bc7fe7633604
/dev/sda1

backup your /etc/fstab file and replace it with the device path instead.

**Comment by s-schweer** [comment]
@hughnet you are aware that there's a pretty good reason for not using device names for anything else then ide disks? The device name is completely unpredictable an can lead to boot issues when adding additional disks

**Comment by roeigo-stratoscale** [comment]
This is also happening if labels are use to activate swap partition in fstab

**Comment by ChrisPortman** [comment]
I've submitted https://github.com/sensu-plugins/sensu-plugins-disk-checks/pull/61 that resolves this

**Comment by ChrisPortman** [comment]
Just wondering when a new release is likely to be made?

**Comment by majormoses** [comment]
@ChrisPortman I will check monday and if this has not been released I will do that when I have some time. If you don't see a release by tues feel free to ping me.

**Comment by majormoses** [comment]
looks like this has been fixed and released. If not reply back and I will re-open.
