### ISSUE TITLE
Incompatible library version with ffi

### ISSUE THREAD

**Issue by captnbp** [sensu-plugins/sensu-plugins-disk-checks#39]
Hi,

I just installed the last version of sensu-client 0.24.1 on my Ubuntu 16.04 from the repository.

All checks work fine, but check-disk-usage.rb doesn't.
I installed it with `sudo gem install sensu-plugins-disk-checks`

When I use it in my shell it works fine. Through Sensu I get this :
`
command : check-disk-usage.rb -w 85 -c 95 -W 85 -K 95 -p /run

output :
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi_c.so (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/structs.rb:1:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:2:in `require_relative'
	from /var/lib/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/filesystem.rb:11:in `require_relative'
	from /var/lib/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/filesystem.rb:11:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/sensu-plugins-disk-checks-1.1.3/bin/check-disk-usage.rb:29:in `<top (required)>'
	from /usr/local/bin/check-disk-usage.rb:23:in `load'
	from /usr/local/bin/check-disk-usage.rb:23:in `<main>'
Invalid check argument(s): invalid option: -w, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mixlib-cli-1.6.0/lib/mixlib/cli.rb:230:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `block in <class:CLI>'"]
`

**Comment by amdprophet** [comment]
Hi @captnbp, can you tell me which version of libffi is installed with `dpkg -l | grep libffi`? I suspect there may be an issue where `ffi_c.so` was built against an incompatible version of libffi.

**Comment by captnbp** [comment]
Quick answer ! 

```
dpkg -l | grep libffi
ii  libffi-dev:amd64                   3.2.1-4                         amd64        Foreign Function Interface library (development files)
ii  libffi6:amd64                      3.2.1-4                         amd64        Foreign Function Interface library runtime
```

**Comment by amdprophet** [comment]
Did this start happening after upgrading Sensu or was this a fresh install?

**Comment by captnbp** [comment]
A fresh install

**Comment by amdprophet** [comment]
Try uninstalling the gem with `sudo gem uninstall sensu-plugins-disk-checks` and then installing with `sensu-install -p disk-checks`.

Using `sensu-install` is the recommended method for installing plugins using Sensu's embedded Ruby. It's possible that some environment variables were not set or set incorrectly when you installed using `gem install`.

Let me know if this fixes the issue for you.

**Comment by captnbp** [comment]
Perfect, this solved my issue ! Many thanks for the trick and globally for the whole solution !

I though the recommended method was the gem one : http://sensu-plugins.io/docs/installation_instructions.html

I like the gem one because it is easy to integrate in Ansible playbooks for my deployments. 
Do you plan to write an Ansible module for sensu-install ?

**Comment by amdprophet** [comment]
I'm happy to hear that the problem is solved.

Using the `gem install` method is fine so long as:
a) `GEM_PATH` and/or `GEM_HOME` environment variables are set correctly.
b) The correct gem binary is being used: `/opt/sensu/embedded/bin/gem`.

**Comment by salmagomaa** [comment]
This might help you
https://github.com/wpscanteam/wpscan/issues/979#issuecomment-370536102
