### ISSUE TITLE
Latest release cannot parse df output on CentOS7

### ISSUE THREAD

**Issue by madAndroid** [sensu-plugins/sensu-plugins-disk-checks#42]
Hi,

We recently bumped our installed version to `2.0.0` - and then started seeing:
```
malformed line from df: /dev/xvda1 xfs 33540488 2805928 30734560 9% /
```
I've not had a chance to further debug this yet, but thought best to create an issue here, in case others run into it as well/

**Comment by madAndroid** [comment]
This output was from `metrics-disk-capacity.rb`

**Comment by mguthmuller** [comment]
The issue exists also on Debian (same error)

**Comment by cwjohnston** [comment]
@madandroid @mguthmuller thanks for reporting this regression. I will look at this shortly.

**Comment by madAndroid** [comment]
Excellent! thank you for the very quick turnaround - I'll test this out as soon as `2.0.1` is released

**Comment by cwjohnston** [comment]
@madAndroid 2.0.1 should be on rubygems now.
