### ISSUE TITLE
device type and device path arguments for check-smart

### ISSUE THREAD

**Issue by GwennG** [sensu-plugins/sensu-plugins-disk-checks#45]
For some controllers (3ware, Areca...), smartctl has to be called with a specific device type (-d|--device) and device path:
smartctl -a -d 3ware,0 /dev/twl0

Auto discovery of devices is great but it could be useful to give the ability to pass device type and device path though command line arguments.

**Comment by ArakniD** [comment]
This should be resolved with #49 with the ability to add override commands per device and override specific SMART elements if required.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-disk-checks/versions/2.4.0
