### ISSUE TITLE
check-smart.rb wont work for 3ware attached disks

### ISSUE THREAD

**Issue by ArakniD** [sensu-plugins/sensu-plugins-disk-checks#48]
When running check-smart.rb with 3ware attached disk I get the following error;

> CheckSMART UNKNOWN: smartctl 6.2 2013-07-26 r3841 [x86_64-linux-3.13.0-91-generic](local build)
> Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org
> 
> Smartctl open device: /dev/sdb failed: AMCC/3ware controller, please try adding '-d 3ware,N',
> you may need to replace /dev/sdb with /dev/twlN, /dev/twaN or /dev/tweN

I've done a crude patch which does;

```
# Generate a list of all block devices
  #
  def scan_disks!
    @number = 0
    `lsblk -nro NAME,TYPE,MODEL`.each_line do |line|
      name, type, model = line.split

      if model == '9650SE-8LP' and type == 'disk'
        @devices << Disk.new("twa0", "-d 3ware,#@number")
        @number += 1
      else
        @devices << Disk.new(name, "") if type == 'disk'
      end
    end
  end
```

An override string per device would be ok, so if an override device path and parameter string existed it then passed that instead of /dev/sd\* to smartctl.

**Comment by majormoses** [comment]
closed via #49
