### ISSUE TITLE
"Critical" raised, when a filesystem is merely warning

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu-plugins/sensu-plugins-disk-checks#56]
I'm seeing an annoying problem here... We run the disk-usage checks thus:

```
 check-disk-usage.rb --warn-space 90 --crit-space 97 --fstype ext2,ext3,ext4,xfs 
```

One one of the filesystems the space-usage is at 91% and thus below the configured "Critical" level. Although the filesystem-specific check is, correctly, reporting a _warning_, the overall check-result is "Critical":

Attaching a snapshot of Uchiwa's page for illustration. Note, how all of the disk-usage subchecks are green, except for _one_, which is yellow. And yet the overall disk-status is "Critical":
![uchiwa-diskcheck](https://cloud.githubusercontent.com/assets/1486340/18923420/155ad12c-857a-11e6-8078-3b9b4e52373f.png)

Using the version 0.0.4 (latest?) of sensu-plugins-disk-usage gem with Sensu-0.26.1. Please, advise.

**Comment by majormoses** [comment]
what do the execution logs say?

**Comment by UnitedMarsupials** [comment]
Sorry, but I'm no longer with that company and can not check.

(Looking for work, by the way!)

**Comment by majormoses** [comment]
@UnitedMarsupials sorry to hear, unless we have any more information to reproduce off I don't know the value of keeping this open as we don't know if it's been fixed in a new version already.

**Comment by majormoses** [comment]
If someone runs into this please re-open or link to this and we will investigate.

**Comment by UnitedMarsupials** [comment]
Seems like verification would be trivial: configure the plugin to run as specified in the ticket and fill up one of the monitored filesystems to exceed the"warning", but below the "critical" threshold. Observe the plugin's behavior...

**Comment by majormoses** [comment]
@UnitedMarsupials my point being I have no idea what versions are causing issues, I don't see this in my environments.

**Comment by majormoses** [comment]
I am open to re-opening if you can re-produce.

**Comment by UnitedMarsupials** [comment]
Oh, Ok. Here, I just installed the gem (0.0.4 remains the latest version available, apparently) on my home computer and ran:

     % check-disk-usage.rb --warn-space 80 --crit-space 90 --fstype ufs
    CheckDiskUsage OK: All filesystems (/, /var, /tmp, /spare) are OK

So far so good. Now, when I lower the warning threshold, to 70% (my `/` is at 78% at the moment), it  becomes "critical" -- incorrectly, it should've become "warning" instead:

     % check-disk-usage.rb --warn-space 70 --crit-space 90 --fstype ufs
     CheckDiskUsage CRITICAL: Found 1 problems

I struggle to understand, why you found it so difficult to verify yourself...

**Comment by majormoses** [comment]
@UnitedMarsupials we have ~170 plugins to manage with a very small number of maintainers that the majority do this in their spare time and do not work for sensu. As I said I am running this check in multiple environments with hundreds of machines and do not see an issue so I asked for someone to reproduce if no one was going to reproduce the issue sits around and no one knows if its still valid or not.

**Comment by majormoses** [comment]
now that I have it confirmed on a specific version I am willing to triage it.

**Comment by majormoses** [comment]
@UnitedMarsupials latest version is https://rubygems.org/gems/sensu-plugins-disk-checks/versions/2.1.0

**Comment by majormoses** [comment]
0.0.4 is VERY old.

**Comment by UnitedMarsupials** [comment]
> 0.0.4 is VERY old. Can you reproduce with newer versions?

0.0.4 is what I get, when I do `gem install sensu-check-disk-usage`. How would I install a newer version? Have you deliberately stopped publishing the gem?

**Comment by majormoses** [comment]
the gem name is wrong, you need `sensu-plugins-disk-usage` as per:
```
$ gem install sensu-check-disk-usage
ERROR:  Could not find a valid gem 'sensu-check-disk-usage' (>= 0) in any repository
ERROR:  Possible alternatives: sensu-plugins-disk-usage, sensu-check-esc, sensu-checks-php-fpm
```

And install:
```
$ gem install sensu-plugins-disk-usage
Fetching: sys-filesystem-1.1.5.gem (100%)
Successfully installed sys-filesystem-1.1.5
Fetching: sensu-plugin-1.2.0.gem (100%)
Successfully installed sensu-plugin-1.2.0
Fetching: sensu-plugins-disk-usage-0.0.4.gem (100%)
You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
rbenv: cannot rehash: /home/babrams/.rbenv/shims/.rbenv-shim exists
Successfully installed sensu-plugins-disk-usage-0.0.4
Parsing documentation for sys-filesystem-1.1.5
Installing ri documentation for sys-filesystem-1.1.5
Parsing documentation for sensu-plugin-1.2.0
Installing ri documentation for sensu-plugin-1.2.0
Parsing documentation for sensu-plugins-disk-usage-0.0.4
Installing ri documentation for sensu-plugins-disk-usage-0.0.4
Done installing documentation for sys-filesystem, sensu-plugin, sensu-plugins-disk-usage after 0 seconds
3 gems installed
```

**Comment by majormoses** [comment]
Also considering the link I sent you is on rubygems.org I am not sure how you would come to the conclusion that we are not publishing it anymore.

**Comment by majormoses** [comment]
@UnitedMarsupials sorry for the confusion, I am guessing that you were still using the old community plugins which has been deprecated for a while: https://github.com/sensu/sensu-community-plugins

**Comment by UnitedMarsupials** [comment]
> now that I have it confirmed on a specific version I am willing to triage it.

I specified the version -- 0.0.4 -- when opening this ticket in September.

> The gem name you are trying to install is wrong, you need sensu-plugins-disk-usage as per

The gem name I'm trying to install is the _original_. Considering, that the new version not only has a different name, but is not _backwards-compatible_ , one can argue, that it is a _different_ gem altogether.

> how you would come to the conclusion that we are not publishing it anymore

My conclusion, obviously, is based on the fact, that `gem install` of the original name still installs the 0.0.4.

Now, trying to run the executable installed by the new gem, I get the following error:
```
% check-disk-usage.rb 
Check failed to run: undefined method `[]' for nil:NilClass, ["/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:185:in `to_human'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:173:in `check_mount'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:132:in `block in fs_mounts'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:121:in `each'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:121:in `fs_mounts'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugins-disk-checks-2.1.0/bin/check-disk-usage.rb:209:in `run'", "/opt/lib/ruby/gems/2.2/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```
Performing `gem update` did not help. Please, advise.

**Comment by UnitedMarsupials** [comment]
BTW, though my original report was based on my work with Linux (RedHat/CentOS) used by my then-employer, my home machine is running FreeBSD. Could it be, the newer versions of the plugin rely on some Linux-only feature of`df(1)`?

**Comment by majormoses** [comment]
I don't see anything from a quick scan of the code that looks linux specific. I will try to spend some time tonight to look into this.

**Comment by UnitedMarsupials** [comment]
If you'd like, I can give you remote access to my FreeBSD system -- just send me the `passwd` entry and the ssh public key: `mi+sensu-2017@aldan.algebra.com`.

**Comment by UnitedMarsupials** [comment]
I tried going back to the older versions and found that 1.1.2 was the last one that worked on FreeBSD. The 1.1.3 is throwing the same error as the latest 2.1.0.

BTW, they all freak out at FreeBSD's devfs, that is always at 100% -- which is perfectly normal... :-)

**Comment by majormoses** [comment]
ok. does the original issue still manifest itself in 1.1.2? Just trying to figure out if we should make an issue for BSD support and close this out.

**Comment by UnitedMarsupials** [comment]
Oh, and the original bug is gone (in 1.1.2):
```
root@aldan:/tmp (1097) check-disk-usage.rb -t ufs -w 80 -c 90
CheckDisk OK: All disk usage under 80% and inode usage under 85%
root@aldan:/tmp (1098) check-disk-usage.rb -t ufs -w 70 -c 90
CheckDisk WARNING: / 79.61% bytes usage (25 GiB/31 GiB)
```
Would you like me to close this ticket and open a new one to track the problem with it not working on FreeBSD?

**Comment by majormoses** [comment]
Yes please, please tag me on it so I can look into it when I have some time if no one gets to it first.
