### ISSUE TITLE
Ignore /dev as default in macOS

### ISSUE THREAD

**Issue by blacksails** [sensu-plugins/sensu-plugins-disk-checks#63]
/dev is a mountpoint which is always at 100% utilization on mac, therefore I would suggest that the mountpoint is simply ignored in macOS.

Currently I work around it by passing `-i '/dev'`

**Comment by mikeshultz** [comment]
FreeBSD, too with any devfs filesystems.  All `devfs` filesystems would probably be the best to ignore.  

    CheckDisk CRITICAL: /dev 100.0% bytes usage (1 KiB/1 KiB), /var/dhcpd/dev 100.0% bytes usage (1 KiB/1 KiB), /cf/named/dev 100.0% bytes usage (1 KiB/1 KiB)
