### ISSUE TITLE
Getting an error CheckDisk WARNING: net:[4026532254] Unable to read on Sensu Server

### ISSUE THREAD

**Issue by dukeforsythe** [sensu-plugins/sensu-plugins-disk-checks#69]
We have installed the check-disk plugin on some servers that have a check-disk warning, but unsure about the file/folder with which it is erroring out on, and not sure what to exclude from the pathing. How do we find that?

**Comment by majormoses** [comment]
@dukeforsythe any chance I can get that info so I at least know which check in the plugin you are talking about? I am not gonna review all of them.

**Comment by majormoses** [comment]
assuming you are running `check-disk-usage.rb` the debug data looks reasonable enough in master:
```
$ ./bin/check-disk-usage.rb 
CheckDisk WARNING: /sys/kernel/debug/tracing Unable to read.
```

I need more info on which version of the check you are running.

**Comment by dukeforsythe** [comment]
You can close this issue, found the info I needed in the new version

Aaron "Duke" Dukleth
503-451-3853

On Jun 11, 2017, at 08:25, Ben Abrams <notifications@github.com<mailto:notifications@github.com>> wrote:


assuming you are running check-disk-usage.rb the debug data looks reasonable enough in master:

$ ./bin/check-disk-usage.rb
CheckDisk WARNING: /sys/kernel/debug/tracing Unable to read.


I need more info on which version of the check you are running.

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-disk-checks/issues/69#issuecomment-307664479
