### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by vadim6** [sensu-plugins/sensu-plugins-disk-checks#70]
Hi,
Is it possible to release a new version for this plugin? There were a couple of fixes committed after 2.0.1 that I need in my monitoring.

Thank you

**Comment by tkaczerski** [comment]
any idea when the new version will get released?

**Comment by majormoses** [comment]
sorry about the delay, I am cutting a release right now.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-disk-checks/versions/2.1.0
