### ISSUE TITLE
Check failed to run: The parameter is incorrect - GetVolumeInformation - Windows

### ISSUE THREAD

**Issue by addi071** [sensu-plugins/sensu-plugins-disk-checks#80]
Hi!

I am using sensu-plugin og Windows platform (2008 R2 and 2012 R2 servers) and I keep receiving following error several times a day:

_Check failed to run: The parameter is incorrect. - GetVolumeInformation, ["C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sys-filesystem-1.1.7/lib/sys/windows/sys/filesystem.rb:209:in `block in mounts'", "C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sys-filesystem-1.1.7/lib/sys/windows/sys/filesystem.rb:181:in `each'", "C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sys-filesystem-1.1.7/lib/sys/windows/sys/filesystem.rb:181:in `mounts'", "C:/opt/sensu/plugins/check-windows-disk.rb:121:in `fs_mounts'", "C:/opt/sensu/plugins/check-windows-disk.rb:206:in `run'", "C:/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.1.0/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]_

Sometimes error disapears in severel minutes by it self, but other times I have to restart service. In some cases error is there for an hour even I ran restart...  I would say that error apears on 5% of monitored hosts, but it is kind of annoying when we are monitoring ca. 300 hosts and when list of hosts affected by this error is continiously changing. 

I couldn't find a pattern to reporduce the error. 

I am running sensu client 1.0. and lates versions of sys-filesystem, sensu-plugin and ffi.

Any suggestions/help would be appreciated.  

Regards, 
adi

**Comment by majormoses** [comment]
@addi071 can you give me the full command you are running and what version of the plugin you have installed?

**Comment by addi071** [comment]
Hi!

The command I am running is as following:
"command": "C:/opt/sensu/embedded/bin/ruby.exe C:/opt/sensu/plugins/check-windows-disk.rb"

Plugin version is 2.1.0.

Tnx.
adi

**Comment by majormoses** [comment]
Looks like this is the wrong repo and you should open against here: https://github.com/sensu-plugins/sensu-plugins-windows

**Comment by addi071** [comment]
My bad! Sorry and thank you.

Regards, 
Adi
