### ISSUE TITLE
Gem install fails due to expired TLS certificate

### ISSUE THREAD

**Issue by alexgottschalkmedal** [sensu-plugins/sensu-plugins-disk-checks#93]
On an Ubuntu 16.04 system with sensu package installed from 1st-party Apt repo:

`root@ubuntu1604:~# /opt/sensu/embedded/bin/gem install sensu-plugins-disk-checks -V -P MediumSecurity

HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=sensu-plugins-disk-checks
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=sensu-plugin,sys-filesystem
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=ffi,json,mixlib-cli
200 OK
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=djberg96/DC=gmail/DC=com not valid after 2016-09-01 20:49:18 UTC`

**Comment by alexgottschalkmedal** [comment]
Disregard, error is for one of ffi, json, or mixlib-cli

**Comment by majormoses** [comment]
Yup nothing on our end. Glad you figured it out.
