### ISSUE TITLE
arugments for check-smart.rb fails

### ISSUE THREAD

**Issue by bdeluca** [sensu-plugins/sensu-plugins-disk-checks#94]
`
/opt/sensu/embedded/bin/check-smart.rb --no-smart-capable-disks ok
Check failed to run: undefined method `to_sym' for false:FalseClass
Did you mean?  to_s, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:290:in `block (3 levels) in opt_parser'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1552:in `block in parse_in_order'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1538:in `catch'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1532:in `order!'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'", "/opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:230:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-disk-checks-3.1.0/bin/check-smart.rb:138:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
`

the argument parse does not like the - characters in the long string.

**Comment by majormoses** [comment]
released https://rubygems.org/gems/sensu-plugins-disk-checks/versions/4.0.0

closed via #95
